-- return {
-- 	{
-- 		"vimwiki/vimwiki",
-- 		init = function()
-- 			vim.g.vimwiki_list = {
-- 				{
-- 					path = "~/Documents/Vim Wiki",
-- 					syntax = "markdown",
-- 					ext = "md",
-- 				},
-- 			}
-- 			vim.g.vimwiki_key_mappings = {
-- 				headers = 0,
-- 			}
-- 			return nil
-- 		end,
-- 	},
-- }
return {}
