-- [nfnl] fnl/config/plugins/snacks.fnl
local dashboard_keys = {{icon = "\239\128\130 ", key = "f", desc = "Find File", action = ":lua Snacks.dashboard.pick('files')"}, {icon = "\239\133\155 ", key = "n", desc = "New File", action = ":ene | startinsert"}, {icon = "\239\128\162 ", key = "g", desc = "Find Text", action = ":lua Snacks.dashboard.pick('live_grep')"}, {icon = "\239\131\133 ", key = "r", desc = "Recent Files", action = ":lua Snacks.dashboard.pick('oldfiles')"}, {icon = "\239\144\163 ", key = "c", desc = "Config", action = ":lua Snacks.dashboard.pick('files', {cwd = vim.fn.stdpath('config')})"}, {icon = "\238\141\136 ", key = "s", desc = "Restore Session", section = "session"}, {icon = "\243\176\146\178 ", key = "L", desc = "Lazy", action = ":Lazy"}, {icon = "\239\144\166 ", key = "q", desc = "Quit", action = ":qa"}, {icon = "\238\152\171 ", key = "w", desc = "Vim Wiki", action = ":VimwikiIndex"}}
local function _1_()
  return {bigfile = {enabled = true}, dashboard = {enabled = true, preset = {keys = dashboard_keys}, sections = {{section = "header"}, {section = "keys", gap = 1, padding = 1}, {section = "startup"}}}, explorer = {enabled = true, replace_netrw = false}, image = {enabled = true}, indent = {enabled = false}, input = {enabled = true}, notifier = {enabled = true}, picker = {enabled = true}, quickfile = {enabled = true}, scope = {enabled = true}, scroll = {enabled = true}, statuscolumn = {enabled = true, right = {"git"}}, words = {enabled = true}}
end
local function _2_(spec, opts)
  local snacks = require("snacks")
  return snacks.setup(opts)
end
return {"folke/snacks.nvim", priority = 1000, opts = _1_, config = _2_, keys = {{"<leader>f", "<cmd>lua require'snacks'.picker.files()<cr>", "File Picker"}, {"<leader>c", "<cmd>lua Snacks.picker.files {cwd = vim.fn.stdpath('config')}<cr>"}, {"<leader>C", "<cmd>lua Snacks.picker.grep {cwd = vim.fn.stdpath('config')}<cr>"}, {"<leader>sg", "<cmd>lua require'snacks'.picker.grep()<cr>", "Live grep"}, {"<leader>,", "<cmd>lua require'snacks'.picker.buffers()<cr>", "Buffers"}, {"<leader>sh", "<cmd>lua require'snacks'.picker.help()<cr>", "Help"}}, lazy = false}
